### ISSUE TITLE
Needed Support on two columns layout?

### ISSUE THREAD

**Issue by Yatoo1992** [minikomi/Bootstrap-Form-Builder#136]
One column layout is working fine but can anyone help on how two implement two columns layout.
thanks.

**Comment by truedeity** [comment]
You mean it should allow horizontal and vertical stacking?  Meaning, it should kind of work like stackpanel element in silverlight as an analogy.  Rather than being limited to one or two columns, you should be able to create any arrangement you want for the elements on the form.  If you only implement two columns someone else is liable to ask for 3 columns later as well.  A better solution to this problem is a kind of Stackpanel analogy of vertical and horizontal orientations would be the right idea.

**Comment by kaoshen** [comment]
I'm working on this problem ,but find it too difficult.

**Comment by minikomi** [comment]
Create elements with two columns.

**Comment by truedeity** [comment]
Create a elements editor?
